/**
 * THIS FILE IS AUTOMATICALLY GENERATED
 * DO NOT EDIT THIS FILE BY HAND
 * THE ROBOTS WILL COME AND EAT YOUR BRAINS
 * 
 * To regenerate this file, run `ruby bin/autogen.rb`. This will regenerate all TS-code protocol enumeration 
 * definitions, as well as the associated strings files used in this program.
 */

#ifndef __tscode_cap_flags_h
#define __tscode_cap_flags_h

#ifdef __cplusplus
extern "C" {
#endif

#include "tscode_units.h"

#define CAP(x) (x - 'A')

enum tscode_cap_flags {
    TSCODE_CAP_AIR_VALVES = CAP('A'), // A
    TSCODE_CAP_MULTIBUFFERS = CAP('B'), // B
    TSCODE_CAP_CONDITIONAL_STOP = CAP('C'), // C
    TSCODE_CAP_LEDS = CAP('D'), // D
    TSCODE_CAP_FANS = CAP('F'), // F
    TSCODE_CAP_HEATERS = CAP('H'), // H
    TSCODE_CAP_LINEAR = CAP('L'), // L
    TSCODE_CAP_MESSAGES = CAP('M'), // M
    TSCODE_CAP_LUBE_PUMPS = CAP('P'), // P
    TSCODE_CAP_RECIPROCATING = CAP('R'), // R
    TSCODE_CAP_SPEAKERS = CAP('S'), // S
    TSCODE_CAP_ROTATING = CAP('T'), // T
    TSCODE_CAP_VIBRATING = CAP('V'), // V
};

typedef enum tscode_cap_flags tscode_cap_flags_t;

#ifdef __cplusplus
}
#endif

#endif